# Generated by Django 6.0 on 2026-01-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_customuser_profile_pic_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
