# Generated by Django 6.0 on 2025-12-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountapp.profile')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100, unique=True)),
                ('subject_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principalapp.department')),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['subject_name'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name'], name='department_departm_6f0352_idx'),
        ),
    ]
