# Generated by Django 6.0 on 2025-12-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
        ('principalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledSubject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principalapp.subject')),
            ],
            options={
                'db_table': 'enrolled_subject',
                'indexes': [models.Index(fields=['student', 'subject'], name='enrolled_su_student_5bbbe6_idx')],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principalapp.subject')),
            ],
            options={
                'db_table': 'exam_result',
                'indexes': [models.Index(fields=['student', 'subject'], name='exam_result_student_292e35_idx')],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
