# Generated by Django 6.0 on 2025-12-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODTutors',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_tutors', to='accountapp.profile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_assigned_by_hod', to='accountapp.profile')),
            ],
            options={
                'db_table': 'hod_tutors',
                'indexes': [models.Index(fields=['hod', 'tutor'], name='hod_tutors_hod_id_810790_idx')],
                'unique_together': {('hod', 'tutor')},
            },
        ),
    ]
