# Generated by Django 6.0 on 2025-12-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
        ('principalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorStudents',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_assigned_to_tutor', to='accountapp.profile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_students', to='accountapp.profile')),
            ],
            options={
                'db_table': 'tutor_students',
                'indexes': [models.Index(fields=['tutor', 'student'], name='tutor_stude_tutor_i_80da6b_idx')],
                'unique_together': {('tutor', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TutorSubjects',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principalapp.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.profile')),
            ],
            options={
                'db_table': 'tutor_subjects',
                'indexes': [models.Index(fields=['tutor', 'subject'], name='tutor_subje_tutor_i_7672ae_idx')],
                'unique_together': {('tutor', 'subject')},
            },
        ),
    ]
